-- 주민번호 보호 강화: ECB 단일컬럼 → 검색용 HMAC 블라인드 인덱스(resident_number) + 복호화용 AES-GCM 암호문(resident_number_enc)
-- resident_number_enc 컬럼 추가 후, 기존 ECB 데이터를 새 형식으로 재암호화(키 교체 포함)한다.
ALTER TABLE `user` ADD COLUMN `resident_number_enc` VARCHAR(255) NULL AFTER `resident_number`;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
UPDATE `user` SET resident_number='bvI6LAgZwph9HxPGrFHIYmxr6scgm2svplJ7ksxYz44=', resident_number_enc='uL9PgQVdoexSAUg5Vmw9x1jINeTum65cgpH6Z9bph/6XTzK6n7fWs8A=' WHERE id=9;
UPDATE `user` SET resident_number='t1QrzrIw/8AqOemy6SM1xm0QqppoorjATgBOCHJ7QpY=', resident_number_enc='+BIA/uD/Ngt5PZic77OyLyy5CLOywd3ZQn1lk1eX7a1kZrTw8Pqj+FA=' WHERE id=2732;
UPDATE `user` SET resident_number='KuTTgawPOs3wiJSxD983CrNkqKzw7f+ByqpCUH190u8=', resident_number_enc='+VWgGTEFkliTpPOuj29xjYoyRPi7NosRLKgU5ReWYGJO+xJBxg6VClI=' WHERE id=2733;
UPDATE `user` SET resident_number='cWk4iwYyeteGG3NwODBxZtoNAr1ho70Vfjsq83c7maY=', resident_number_enc='gwEW/rdCLVfIgci1oX6vaYHrJN1dx7fB1/KfQtREpqZJNhwKAc932uM=' WHERE id=2734;
UPDATE `user` SET resident_number='vAVwaswMYt5mGbXVxjSuK8Fd9Mbmy3boVBTMcIUk6JU=', resident_number_enc='OBqWqbzWRxY2Xb4hkyWseJb458ICtohn3VMyZ+FR3fVOKE4eml9OYg8=' WHERE id=2735;
UPDATE `user` SET resident_number='xyHj9tecivnruzOqobAeo2ydzpTBf9+jzbVOJcjh39w=', resident_number_enc='TFC9PsCAsipdaILITeM6ytWEfb+E02459TVo8m/6sjF11+TzTkbybKM=' WHERE id=2736;
UPDATE `user` SET resident_number='vqiH+VYim3FTTjLGIfhmIVR5ZW4CrxuAjwWHpwnlDkc=', resident_number_enc='tpvcl8qXPoacYV93CimqmjUgi4LCH0kKMs+9NX6OrKCTABWs1R+z12U=' WHERE id=2737;
UPDATE `user` SET resident_number='t3cLVjCRJmUVq4fzLC/lumF1Uas6R7VBD1sw7lZl3OY=', resident_number_enc='irITyllGq5rhmpWIZl4C8jI1t3HKR5/OoDi3AJiwiIptQZfS5hPjClw=' WHERE id=2738;
UPDATE `user` SET resident_number='A3DXX8DF3L0+onDOOODIaEd+UEe4E+c9Wpxl/p2JEgQ=', resident_number_enc='ECV75GLxJKnvZGxwgKhRoOaK/aABimaGDqyao7PtPyx+UdtXZ2OhkMA=' WHERE id=2739;
UPDATE `user` SET resident_number='t3YNzZakhGchBL6T7N+9kWrDbexIE9lp/w0+sVGSIoY=', resident_number_enc='42cD0X+SG0mTcC0uOmbKkIb1JDvQj6plW8heSfa2e+MXAGYmhEEyjWg=' WHERE id=2740;
UPDATE `user` SET resident_number='xvJidhw3/tsucsLKGvERq2Syud4lpxb6qsTKw8KjcoA=', resident_number_enc='5LgxAhAhMoBacloPqCR57p3l59o2tcLNxLTHzSUmdALWM4YjTysfMkQ=' WHERE id=2741;
UPDATE `user` SET resident_number='iuvFlFBoAkKrDeld2n012Z2eXAMeFdzeTYOoneGMsu0=', resident_number_enc='v2FMzLKZ9TmxAub6jIO0pNtEfBMsSnlGF7BUPwEpaQHVf5qDU5SwOv0=' WHERE id=2742;
UPDATE `user` SET resident_number='MJ1SZxpC/vu3+Qc2JzKhsSDs0cOmb/b0/UJCx1gph7U=', resident_number_enc='gIX39zMrqxbXukfJ6/bdObQgUpySxqC/Xgs5vuQL/jzkmcAbVTJssFA=' WHERE id=2743;
UPDATE `user` SET resident_number='HwnTlHTtBOBggGid6ngzQzBqD+yfOky+rduNlcC29P0=', resident_number_enc='2Dsvnaud0iZMFTADFjEcLc9UewnjmLi28X+UuwfTphIztFy+CtPK9NY=' WHERE id=2744;
UPDATE `user` SET resident_number='iD7N9m8WIwtLDHggOYTvZBgA8tsSqYZly8x9rRlG3+w=', resident_number_enc='HMlvDi0XkhdwQ81RSEUYVmKcFCYmJub8d7cQIVnSnVRAo9TRYJvYDew=' WHERE id=2745;
UPDATE `user` SET resident_number='IeAg527Fz/wB304kQw58ZdZJSCWO7vQYyALLFOmMHnw=', resident_number_enc='Fnxn6X93DoBMWlFtfk8rvZ4yQYjohxl755BeeBxKPpfwhzZyDUyOSrI=' WHERE id=2746;
UPDATE `user` SET resident_number='OG1EYrN0PnVVKfAuJEracIbEaMuUMEUc0qr+/lTzjQI=', resident_number_enc='vFug6+joPTdLzUdrnFUfz3QRyVBRAmcjTbMTyS5ycOWTmK9kyrto9SY=' WHERE id=2747;
UPDATE `user` SET resident_number='jf5F8qYk4jSs12jIZGb7lUJ9NtWNIzPN8Iz/iAfj/zI=', resident_number_enc='X2/9kZoCaidGP+v+KDiJT5lswpz5s1XH6pYYjy+5//moN96RcihMqJU=' WHERE id=2748;
UPDATE `user` SET resident_number='RO9HTF0KEHKQV0O/RFlb/8ZY59o060cSXCyYTcwRP1Q=', resident_number_enc='7+ut4Z3xXuAuKtY4tVefvcOmVj57FebdskDnI8pVKGX+iDDD5TovS2g=' WHERE id=2749;
UPDATE `user` SET resident_number='sHWAlkpYIF2LajB0nN/ni6nq9+6lDeUaIkr4uNUOx2o=', resident_number_enc='Yaua7L5BoiNFtv/cZOgJea+ppP2M53xfJ1ldzOZNKVPIJjrkJHoDdhM=' WHERE id=2751;
UPDATE `user` SET resident_number='vk7mVaBZKcetFRgqLEsf/+jr+gztJSuZRwyl0ZTADwk=', resident_number_enc='4mkQvCoL1WO5hSb2aNYO0Hy/Cb1qxwhnQLJAmxxZ6A+1ssxUloB/IPc=' WHERE id=2752;
UPDATE `user` SET resident_number='ePWEDGN1lwrPVJUxy2teL88CvLqGyUmJ/futIiZa0sc=', resident_number_enc='xE+BhD1Q4qxfsNTO4RbRYEFJhzi8les0MNAsElOZPv2dovHyPWl+Z+M=' WHERE id=2754;
UPDATE `user` SET resident_number='doZxAeMa/cq64bQFNSG3VU0mq7TtqSzW56bsj6af9kA=', resident_number_enc='XEO17YVFIWPTecCGq9YeUuSsJKCFRbdCsztObADuVcwQv4m5DgMWkSE=' WHERE id=2757;
UPDATE `user` SET resident_number='ZnSEz8bD7gtXLM+IQd3cvMtZyZKN5dtu18ti9ADFBV8=', resident_number_enc='+Z1/ofDD4EGWvTQP42MIpSdntQhBlWi5LI1v1Ef9F4jLUNv3vwCuvwQ=' WHERE id=2760;
UPDATE `user` SET resident_number='rQAH9aqC5BGyevtod3PHlefGdbR/QPZAZ4FrR8UXrqk=', resident_number_enc='aG4dlmzPwpWL3cL8Ldc+aF1g68AK3lkDKm+dl3LF6xhj6Skknk2laqE=' WHERE id=2761;
SET FOREIGN_KEY_CHECKS=1;
